// <auto-generated />
using System;
using HospitalManagement.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250316041412_Init_Database")]
    partial class Init_Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitalManagement.DataAccess.Entities.Admission", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AttendingDoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientId", "AdmissionDate");

                    b.HasIndex("AttendingDoctorId");

                    b.ToTable("Admissions");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            AdmissionDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 1,
                            Diagnosis = "Hypertension",
                            DischargeDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 2,
                            AdmissionDate = new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 2,
                            Diagnosis = "Pneumonia",
                            DischargeDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 3,
                            AdmissionDate = new DateTime(2023, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 3,
                            Diagnosis = "Fractured Leg",
                            DischargeDate = new DateTime(2023, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 4,
                            AdmissionDate = new DateTime(2023, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 5,
                            Diagnosis = "Migraine",
                            DischargeDate = new DateTime(2023, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 5,
                            AdmissionDate = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 7,
                            Diagnosis = "Appendicitis",
                            DischargeDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 6,
                            AdmissionDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 2,
                            Diagnosis = "Asthma",
                            DischargeDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 7,
                            AdmissionDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 4,
                            Diagnosis = "Skin Infection",
                            DischargeDate = new DateTime(2023, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 8,
                            AdmissionDate = new DateTime(2023, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 8,
                            Diagnosis = "Depression",
                            DischargeDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 9,
                            AdmissionDate = new DateTime(2023, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 9,
                            Diagnosis = "Diabetes",
                            DischargeDate = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 10,
                            AdmissionDate = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 10,
                            Diagnosis = "Allergic Reaction",
                            DischargeDate = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 11,
                            AdmissionDate = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 2,
                            Diagnosis = "Bronchitis",
                            DischargeDate = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 12,
                            AdmissionDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 10,
                            Diagnosis = "Food Allergy",
                            DischargeDate = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 13,
                            AdmissionDate = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 3,
                            Diagnosis = "Back Pain",
                            DischargeDate = new DateTime(2023, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 14,
                            AdmissionDate = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 5,
                            Diagnosis = "Migraine",
                            DischargeDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 15,
                            AdmissionDate = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 1,
                            Diagnosis = "Hypertension",
                            DischargeDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 16,
                            AdmissionDate = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 2,
                            Diagnosis = "Asthma",
                            DischargeDate = new DateTime(2023, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 17,
                            AdmissionDate = new DateTime(2023, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 4,
                            Diagnosis = "Skin Rash",
                            DischargeDate = new DateTime(2023, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 18,
                            AdmissionDate = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 8,
                            Diagnosis = "Anxiety",
                            DischargeDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 19,
                            AdmissionDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 9,
                            Diagnosis = "Diabetes",
                            DischargeDate = new DateTime(2023, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 20,
                            AdmissionDate = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 10,
                            Diagnosis = "Allergic Reaction",
                            DischargeDate = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 1,
                            AdmissionDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 2,
                            Diagnosis = "Flu",
                            DischargeDate = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 3,
                            AdmissionDate = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 3,
                            Diagnosis = "Fractured Arm",
                            DischargeDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 5,
                            AdmissionDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttendingDoctorId = 7,
                            Diagnosis = "Stomach Pain",
                            DischargeDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HospitalManagement.DataAccess.Entities.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            FirstName = "John",
                            LastName = "Smith",
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            DoctorId = 2,
                            FirstName = "Emily",
                            LastName = "Johnson",
                            Specialty = "Pediatrics"
                        },
                        new
                        {
                            DoctorId = 3,
                            FirstName = "Michael",
                            LastName = "Brown",
                            Specialty = "Orthopedics"
                        },
                        new
                        {
                            DoctorId = 4,
                            FirstName = "Sarah",
                            LastName = "Davis",
                            Specialty = "Dermatology"
                        },
                        new
                        {
                            DoctorId = 5,
                            FirstName = "David",
                            LastName = "Wilson",
                            Specialty = "Neurology"
                        },
                        new
                        {
                            DoctorId = 6,
                            FirstName = "Laura",
                            LastName = "Martinez",
                            Specialty = "Oncology"
                        },
                        new
                        {
                            DoctorId = 7,
                            FirstName = "James",
                            LastName = "Anderson",
                            Specialty = "Gastroenterology"
                        },
                        new
                        {
                            DoctorId = 8,
                            FirstName = "Emma",
                            LastName = "Taylor",
                            Specialty = "Psychiatry"
                        },
                        new
                        {
                            DoctorId = 9,
                            FirstName = "Daniel",
                            LastName = "Thomas",
                            Specialty = "Endocrinology"
                        },
                        new
                        {
                            DoctorId = 10,
                            FirstName = "Olivia",
                            LastName = "Moore",
                            Specialty = "Rheumatology"
                        });
                });

            modelBuilder.Entity("HospitalManagement.DataAccess.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PatientId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Allergies = "Peanuts",
                            BirthDate = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Toronto",
                            FirstName = "Alice",
                            Gender = "F",
                            Height = 165m,
                            LastName = "Johnson",
                            ProvinceId = "ON",
                            Weight = 70m
                        },
                        new
                        {
                            PatientId = 2,
                            BirthDate = new DateTime(1985, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Vancouver",
                            FirstName = "Bob",
                            Gender = "M",
                            Height = 180m,
                            LastName = "Williams",
                            ProvinceId = "BC",
                            Weight = 85m
                        },
                        new
                        {
                            PatientId = 3,
                            Allergies = "Shellfish",
                            BirthDate = new DateTime(1978, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Calgary",
                            FirstName = "Charlie",
                            Gender = "M",
                            Height = 175m,
                            LastName = "Brown",
                            ProvinceId = "AB",
                            Weight = 90m
                        },
                        new
                        {
                            PatientId = 4,
                            Allergies = "Pollen",
                            BirthDate = new DateTime(1995, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Montreal",
                            FirstName = "Diana",
                            Gender = "F",
                            Height = 160m,
                            LastName = "Miller",
                            ProvinceId = "QC",
                            Weight = 60m
                        },
                        new
                        {
                            PatientId = 5,
                            BirthDate = new DateTime(2000, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Winnipeg",
                            FirstName = "Ethan",
                            Gender = "M",
                            Height = 170m,
                            LastName = "Davis",
                            ProvinceId = "MB",
                            Weight = 75m
                        },
                        new
                        {
                            PatientId = 6,
                            Allergies = "Dust",
                            BirthDate = new DateTime(1982, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Saskatoon",
                            FirstName = "Fiona",
                            Gender = "F",
                            Height = 168m,
                            LastName = "Garcia",
                            ProvinceId = "SK",
                            Weight = 68m
                        },
                        new
                        {
                            PatientId = 7,
                            Allergies = "Penicillin",
                            BirthDate = new DateTime(1992, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Halifax",
                            FirstName = "George",
                            Gender = "M",
                            Height = 182m,
                            LastName = "Rodriguez",
                            ProvinceId = "NS",
                            Weight = 88m
                        },
                        new
                        {
                            PatientId = 8,
                            BirthDate = new DateTime(1988, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Fredericton",
                            FirstName = "Hannah",
                            Gender = "F",
                            Height = 155m,
                            LastName = "Martinez",
                            ProvinceId = "NB",
                            Weight = 55m
                        },
                        new
                        {
                            PatientId = 9,
                            Allergies = "Latex",
                            BirthDate = new DateTime(1975, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "St. Johns",
                            FirstName = "Ian",
                            Gender = "M",
                            Height = 178m,
                            LastName = "Hernandez",
                            ProvinceId = "NL",
                            Weight = 82m
                        },
                        new
                        {
                            PatientId = 10,
                            Allergies = "Nuts",
                            BirthDate = new DateTime(1998, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Charlottetown",
                            FirstName = "Jessica",
                            Gender = "F",
                            Height = 162m,
                            LastName = "Lopez",
                            ProvinceId = "PE",
                            Weight = 65m
                        },
                        new
                        {
                            PatientId = 11,
                            Allergies = "Pollen",
                            BirthDate = new DateTime(1993, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Edmonton",
                            FirstName = "Kevin",
                            Gender = "M",
                            Height = 172m,
                            LastName = "Lee",
                            ProvinceId = "AB",
                            Weight = 78m
                        },
                        new
                        {
                            PatientId = 12,
                            Allergies = "Shellfish",
                            BirthDate = new DateTime(1987, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Victoria",
                            FirstName = "Linda",
                            Gender = "F",
                            Height = 160m,
                            LastName = "Clark",
                            ProvinceId = "BC",
                            Weight = 62m
                        },
                        new
                        {
                            PatientId = 13,
                            BirthDate = new DateTime(1976, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Regina",
                            FirstName = "Mike",
                            Gender = "M",
                            Height = 185m,
                            LastName = "Lewis",
                            ProvinceId = "SK",
                            Weight = 92m
                        },
                        new
                        {
                            PatientId = 14,
                            Allergies = "Penicillin",
                            BirthDate = new DateTime(1991, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Ottawa",
                            FirstName = "Nancy",
                            Gender = "F",
                            Height = 158m,
                            LastName = "Walker",
                            ProvinceId = "ON",
                            Weight = 57m
                        },
                        new
                        {
                            PatientId = 15,
                            Allergies = "Dust",
                            BirthDate = new DateTime(1984, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Quebec City",
                            FirstName = "Oscar",
                            Gender = "M",
                            Height = 177m,
                            LastName = "Hall",
                            ProvinceId = "QC",
                            Weight = 80m
                        },
                        new
                        {
                            PatientId = 16,
                            BirthDate = new DateTime(2002, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Winnipeg",
                            FirstName = "Patricia",
                            Gender = "F",
                            Height = 163m,
                            LastName = "Young",
                            ProvinceId = "MB",
                            Weight = 65m
                        },
                        new
                        {
                            PatientId = 17,
                            Allergies = "Latex",
                            BirthDate = new DateTime(1997, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Halifax",
                            FirstName = "Quincy",
                            Gender = "M",
                            Height = 180m,
                            LastName = "Allen",
                            ProvinceId = "NS",
                            Weight = 85m
                        },
                        new
                        {
                            PatientId = 18,
                            Allergies = "Nuts",
                            BirthDate = new DateTime(1989, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Fredericton",
                            FirstName = "Rachel",
                            Gender = "F",
                            Height = 167m,
                            LastName = "King",
                            ProvinceId = "NB",
                            Weight = 70m
                        },
                        new
                        {
                            PatientId = 19,
                            BirthDate = new DateTime(1979, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "St. Johns",
                            FirstName = "Steve",
                            Gender = "M",
                            Height = 175m,
                            LastName = "Wright",
                            ProvinceId = "NL",
                            Weight = 77m
                        },
                        new
                        {
                            PatientId = 20,
                            Allergies = "Peanuts",
                            BirthDate = new DateTime(1994, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Charlottetown",
                            FirstName = "Tina",
                            Gender = "F",
                            Height = 162m,
                            LastName = "Scott",
                            ProvinceId = "PE",
                            Weight = 60m
                        });
                });

            modelBuilder.Entity("HospitalManagement.DataAccess.Entities.Province", b =>
                {
                    b.Property<string>("ProvinceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.ToTable("ProvinceNames");

                    b.HasData(
                        new
                        {
                            ProvinceId = "ON",
                            ProvinceName = "Ontario"
                        },
                        new
                        {
                            ProvinceId = "BC",
                            ProvinceName = "British Columbia"
                        },
                        new
                        {
                            ProvinceId = "AB",
                            ProvinceName = "Alberta"
                        },
                        new
                        {
                            ProvinceId = "QC",
                            ProvinceName = "Quebec"
                        },
                        new
                        {
                            ProvinceId = "MB",
                            ProvinceName = "Manitoba"
                        },
                        new
                        {
                            ProvinceId = "SK",
                            ProvinceName = "Saskatchewan"
                        },
                        new
                        {
                            ProvinceId = "NS",
                            ProvinceName = "Nova Scotia"
                        },
                        new
                        {
                            ProvinceId = "NB",
                            ProvinceName = "New Brunswick"
                        },
                        new
                        {
                            ProvinceId = "NL",
                            ProvinceName = "Newfoundland and Labrador"
                        },
                        new
                        {
                            ProvinceId = "PE",
                            ProvinceName = "Prince Edward Island"
                        },
                        new
                        {
                            ProvinceId = "NT",
                            ProvinceName = "Northwest Territories"
                        },
                        new
                        {
                            ProvinceId = "YT",
                            ProvinceName = "Yukon"
                        },
                        new
                        {
                            ProvinceId = "NU",
                            ProvinceName = "Nunavut"
                        });
                });

            modelBuilder.Entity("HospitalManagement.DataAccess.Entities.Admission", b =>
                {
                    b.HasOne("HospitalManagement.DataAccess.Entities.Doctor", "AttendingDoctor")
                        .WithMany()
                        .HasForeignKey("AttendingDoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagement.DataAccess.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendingDoctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagement.DataAccess.Entities.Patient", b =>
                {
                    b.HasOne("HospitalManagement.DataAccess.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });
#pragma warning restore 612, 618
        }
    }
}
